name: quizmonke
description: Learn Anything, Anywhere, Instantly.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.1+15

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.9.0
  firebase_crashlytics: ^3.3.7
  firebase_storage: ^11.2.7
  firebase_analytics: ^10.5.1
  firebase_app_check: ^0.2.0
  firebase_ui_auth: ^1.8.0
  firebase_ui_oauth_google: ^1.2.11
  cloud_firestore: ^4.9.3
  cloud_functions: ^4.4.1
  google_fonts: ^6.1.0
  google_mobile_ads: ^3.1.0
  google_sign_in: ^6.1.5
  camera: ^0.10.5+4
  provider: ^6.0.5
  flutter_markdown: ^0.6.17+3
  file_picker: ^5.5.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 28
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#f5f5f5"
    theme_color: "#161416"